### ISSUE TITLE
aplicação Flask indisponível

### ISSUE THREAD

**Issue by mensageirodobem** [rmohandasrodrigues/clientes#1]
1. Executo a aplicação com docker-compose: `docker compose -f "docker-compose.yml" up -d --build`
2. No endereço do navegador informo `http://localhost:5000/`
3.
![image](https://github.com/user-attachments/assets/778caeb5-9b9b-4362-8ca0-1a98cfeaa680)

Obs.: http://localhost:8000 está respondendo.

**Comment by rmohandasrodrigues** [comment]
Vou dar uma olhada e realizo a correção.

**Comment by rmohandasrodrigues** [comment]
Realizei os testes tanto localmente como no container tinha dado certo!

**Comment by rmohandasrodrigues** [comment]
Consegui identificar o erro estou realizando a correção!

**Comment by rmohandasrodrigues** [comment]
Correção aplicada poderia tentar atualizar o projeto e executar por favor.

**Comment by rmohandasrodrigues** [comment]
![image](https://github.com/user-attachments/assets/b7fd7f90-d90b-4a2d-9b75-7aab4321a670)

**Comment by rmohandasrodrigues** [comment]
![image](https://github.com/user-attachments/assets/21397443-e36b-497e-8486-280350844749)

**Comment by rmohandasrodrigues** [comment]
![image](https://github.com/user-attachments/assets/c4b544d9-0198-44b6-a372-7b27d6d52749)

**Comment by rmohandasrodrigues** [comment]
![image](https://github.com/user-attachments/assets/f4e7716e-022c-4ebf-8bc5-6fbbc06e895c)
